# -- Override full name
fullnameOverride: ""
# -- Override name
nameOverride: ""

# -- Replica count
replicaCount: 1
image:
  # -- Image repository
  repository: ghcr.io/sap/image-mapper
  # -- Image tag (defauls to .Chart.AppVersion)
  tag: ""
  # -- Image pull policy
  pullPolicy: IfNotPresent
# -- Image pull secrets
imagePullSecrets: []
# -- Node selector
nodeSelector: {}
# -- Affinity settings
affinity: {}
# -- Topology spread constraints (if unspecified, default constraints for hostname and zone will be generated)
topologySpreadConstraints: []
# -- Default topology spread policy for hostname
defaultHostNameSpreadPolicy: ScheduleAnyway
# -- Default topology spread policy for zone
defaultZoneSpreadPolicy: ScheduleAnyway
# -- Tolerations
tolerations: []
# -- Priority class
priorityClassName: ""
# -- Pod security context
podSecurityContext: {}
# -- Additional pod annotations
podAnnotations: {}
# -- Additional pod labels
podLabels: {}
# -- Container security context
securityContext: {}
resources:
  limits:
    # -- Memory limit
    memory: 128Mi
    # -- CPU limit
    cpu: 100m
  requests:
    # -- Memory request
    memory: 128Mi
    # -- CPU request
    cpu: 100m
dnsPolicy: ClusterFirst
hostNetwork: false

pdb:
  # -- Whether to create a PodDisruptionBudget for the webhook
  enabled: true
  # -- Labels to set on the PodDisruptionBudget
  labels: {}
  # -- Annotations to set on the PodDisruptionBudget
  annotations: {}
  # -- Number of pods that are available after eviction as number or percentage (e.g. 50%)
  # @default -- `"1"` (defaults to 1 if not specified)
  minAvailable: "1"
  # -- Number of pods that are unavailable after eviction as number or percentage (e.g: 50%); has higher precedence over `pdb.minAvailable`
  maxUnavailable: ""

webhook:
  certManager:
    # -- Whether to use cert-manager to manage webhook tls
    enabled: false
    # -- Issuer group (only relevant if enabled is true; if unset, the default cert-manager group is used)
    issuerGroup: ""
    # -- Issuer kind (only relevant if enabled is true; if unset, the default cert-manager type 'Issuer' is used)
    issuerKind: ""
    # -- Issuer name (only relevant if enabled is true; if unset, a self-signed issuer is used)
    issuerName: ""
  objectSelector:
    # -- Object selector matchLabels, used by webhook
    matchLabels: {}
    # -- Object selector matchExpressions, used by webhook
    matchExpressions: []
  namespaceSelector:
    # -- Namespace selector matchLabels, used by webhook
    matchLabels: {}
    # -- Namespace selector matchExpressions, used by webhook
    matchExpressions: []
  # -- Match conditions for webhooks can be used for fine-grained request filtering. Docs: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-matchconditions
  matchConditions: []
  # -- Examples from documentation:
  # -- - name: 'exclude-leases' # Each match condition must have a unique name
  # --   expression: '!(request.resource.group == "coordination.k8s.io" && request.resource.resource == "leases")' # Match non-lease resources.
  # -- - name: 'exclude-kubelet-requests'
  # --   expression: '!("system:nodes" in request.userInfo.groups)' # Match requests made by non-node users.
  # -- - name: 'rbac' # Skip RBAC requests, which are handled by the second webhook.
  # --   expression: 'request.resource.group != "rbac.authorization.k8s.io"'

  # -- Timeout in seconds for the webhook call. Must be between 1 and 30 seconds.
  timeoutSeconds: 10

  # -- What to do if the webhook call fails.
  # -- Valid values: "Ignore", "Fail"
  failurePolicy: Fail

  # -- Policy for matching incoming requests to webhook rules.
  # -- Valid values: "Exact", "Equivalent"
  matchPolicy: Equivalent

  # -- Indicates whether calling the webhook has side effects.
  # -- Valid values: "None", "Some"
  sideEffects: None

  # -- Reinvocation policy defines whether the webhook should be called again
  # -- Valid values: "Never", "IfNeeded"
  reinvocationPolicy: IfNeeded

# -- Log level
logLevel: 0
# -- Mapping rules
mapping: []
# -- Labels to set on mutated pods
labelsAddedIfModified: {}
# -- Annotations to set on mutated pods
annotationsAddedIfModified: {}

# -- Service configuration
service:
  # -- The external port exposed by the service
  port: 443
  # -- Protocol to use (TCP/UDP). Default is TCP.
  protocol: TCP
  # -- Target port on the pod (usually a named port or containerPort)
  targetPort: webhooks
  # -- Name for the port (used for things like Prometheus scraping and readability)
  name: https
